description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  http: ^1.1.2
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  cupertino_icons: ^1.0.8

  # ✅ جدیدترین نسخه‌های Firebase
  firebase_core: ^2.27.0
  firebase_auth: ^4.19.0
  firebase_storage: ^11.6.0
  firebase_database: ^10.4.9
  cloud_firestore: ^4.15.0

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutterfire_cli: ^0.2.7 # ✅ این باید در dev_dependencies باشد!

flutter:
  generate: true
  assets:
    - lib/l10n/
    - assets/images/logo.png
  uses-material-design: true
